name: Collect release info

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  update-release-info:
    runs-on: ubuntu-20.04
    steps:
      - name: Update info about the latest release in musescore-updates
        run: |
          sudo bash ./build/ci/release/update_latest_release_info.sh
