name: Collect release info

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  update-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update info about the latest release in musescore-updates
        run: |
          sudo bash ./build/ci/release/update_latest_release_info.sh \
            ${{ secrets.GITHUB_TOKEN }} \
            ${{ github.repository }} \
            ${{ secrets.S3_KEY }} \
            ${{ secrets.S3_SECRET }} \
            "s3://musescore-updates/feed/" \
            "s3.musescore-updates"
