name: Send release info

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  send-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Send release info
        run: |
          echo "START"

          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest > ${RELEASE_INFO}

          echo "Release info = ${RELEASE_INFO}"
